import { act, cleanup, render, screen } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { afterEach, expect, it, vi } from 'vitest'
import { HomeCompanion, UserAvatarPresence } from './HomeCompanion'
vi.mock('../../modules/user-avatar', () => ({ UserAvatar: ({ id }: { id: string }) => <span>{id}</span> }))
vi.mock('../../modules/agent-profile', () => ({ readAgentProfile: vi.fn() }))
afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals() })
it('does not render a product mascot when no user avatar is selected', () => {
  const client = new QueryClient()
  render(<QueryClientProvider client={client}><HomeCompanion active /></QueryClientProvider>)
  expect(document.querySelector('.hm-companion')).toBeNull()
  client.clear()
})
it('keeps the selected avatar mounted for its exit then peeks on returning home', () => {
  vi.useFakeTimers()
  const view = render(<UserAvatarPresence active avatar={{ id: 'xiaoping' }} />)
  view.rerender(<UserAvatarPresence active={false} avatar={{ id: 'xiaoping' }} />)
  expect(screen.getByText('xiaoping').parentElement).toHaveAttribute('data-away', 'true')
  act(() => { vi.advanceTimersByTime(449) })
  expect(screen.getByText('xiaoping')).toBeInTheDocument()
  act(() => { vi.advanceTimersByTime(1) })
  expect(screen.queryByText('xiaoping')).not.toBeInTheDocument()
  view.rerender(<UserAvatarPresence active avatar={{ id: 'xiaoping' }} />)
  expect(screen.getByText('xiaoping').parentElement).toHaveAttribute('data-away', 'false')
})
it('finishes the old person leaving before peeking the new one and coalesces quick swaps', () => {
  vi.useFakeTimers()
  const view = render(<UserAvatarPresence active avatar={{ id: 'xiaoping' }} />)
  view.rerender(<UserAvatarPresence active avatar={{ id: 'mo' }} />)
  expect(screen.getByText('xiaoping').parentElement).toHaveAttribute('data-away', 'true')
  expect(screen.queryByText('mo')).not.toBeInTheDocument()
  act(() => { vi.advanceTimersByTime(200) })
  view.rerender(<UserAvatarPresence active avatar={{ id: 'cat' }} />)
  act(() => { vi.advanceTimersByTime(250) })
  expect(screen.queryByText('xiaoping')).not.toBeInTheDocument()
  expect(screen.queryByText('mo')).not.toBeInTheDocument()
  expect(screen.getByText('cat').parentElement).toHaveAttribute('data-away', 'false')
})
it('applies colors without replaying peek and cancels departure on a rapid return', () => {
  vi.useFakeTimers()
  const view = render(<UserAvatarPresence active avatar={{ id: 'mo' }} />)
  const root = screen.getByText('mo').parentElement
  view.rerender(<UserAvatarPresence active avatar={{ id: 'mo', hair: '#123456' }} />)
  expect(screen.getByText('mo').parentElement).toBe(root)
  view.rerender(<UserAvatarPresence active={false} avatar={{ id: 'mo' }} />)
  act(() => { vi.advanceTimersByTime(200) })
  view.rerender(<UserAvatarPresence active avatar={{ id: 'mo' }} />)
  act(() => { vi.advanceTimersByTime(500) })
  expect(screen.getByText('mo').parentElement).toHaveAttribute('data-away', 'false')
})
it('immediately hides or replaces avatars for reduced motion', () => {
  vi.stubGlobal('matchMedia', () => ({ matches: true }))
  const view = render(<UserAvatarPresence active avatar={{ id: 'xiaoping' }} />)
  view.rerender(<UserAvatarPresence active avatar={{ id: 'cat' }} />)
  expect(screen.getByText('cat')).toBeInTheDocument()
  view.rerender(<UserAvatarPresence active avatar={null} />)
  expect(screen.queryByText('cat')).not.toBeInTheDocument()
})

it('keeps the original 400ms entry delay for a profile arriving asynchronously and route re-entry', () => {
  vi.useFakeTimers()
  const view = render(<UserAvatarPresence active avatar={null} />)
  view.rerender(<UserAvatarPresence active avatar={{ id: 'xiaoping' }} />)
  expect(screen.getByText('xiaoping').parentElement).toHaveAttribute('data-swapped', 'false')
  view.rerender(<UserAvatarPresence active={false} avatar={{ id: 'xiaoping' }} />)
  act(() => { vi.advanceTimersByTime(450) })
  view.rerender(<UserAvatarPresence active avatar={{ id: 'xiaoping' }} />)
  expect(screen.getByText('xiaoping').parentElement).toHaveAttribute('data-swapped', 'false')
})
it('uses delay-free peek only after the old person finishes leaving for a different person', () => {
  vi.useFakeTimers()
  const view = render(<UserAvatarPresence active avatar={{ id: 'xiaoping' }} />)
  view.rerender(<UserAvatarPresence active avatar={{ id: 'mo' }} />)
  act(() => { vi.advanceTimersByTime(450) })
  expect(screen.getByText('mo').parentElement).toHaveAttribute('data-swapped', 'true')
})
