import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, Route, Routes, useLocation } from 'react-router'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { WritingHomePage } from './WritingHomePage'
import { WritingDocumentEditor } from './WritingDocumentPage'
import { writingApi } from '../../modules/writing'
import { draftKey } from './writingState'
vi.mock('../../modules/writing', async importOriginal => ({ ...await importOriginal<typeof import('../../modules/writing')>(), writingApi: { summary: vi.fn(), samples: vi.fn(), document: vi.fn(), revisions: vi.fn(), create: vi.fn(), update: vi.fn(), propose: vi.fn(), resolve: vi.fn(), upload: vi.fn(), previewSamples: vi.fn(), createSample: vi.fn(), deleteSample: vi.fn() } }))
vi.mock('../../modules/agent-profile', () => ({ readAgentProfile: vi.fn(async () => ({ name: '澄', avatar_id: 'cheng', color: '#000' })) }))
vi.mock('../../modules/agent-avatar', () => ({ AgentAvatar: () => <span>头像</span> }))
vi.mock('../ui/PageShell', () => ({ PageShell: ({ children }: { children: React.ReactNode }) => <div>{children}</div> }))
vi.mock('../ui/Select', () => ({ Select: ({ options, onChange, ...props }: { options: { value: string; label: string }[]; onChange(value: string): void }) => <select {...props} onChange={event => onChange(event.target.value)}>{options.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select> }))
vi.mock('../../modules/shared-editor', () => ({ SharedEditor: ({ markdown, onChange, readOnly }: { markdown: string; onChange(value: string): void; readOnly?: boolean }) => <textarea aria-label="Markdown 源码" value={markdown} onChange={event => onChange(event.target.value)} readOnly={readOnly} /> }))
vi.mock('../agent/ResearchAgentConversationPage', () => ({ ResearchAgentConversationPage: () => <div>公共 Agent 面板</div> }))
const doc = { document_id: 'doc-1', title: '原题', genre: 'essay' as const, markdown: '原文内容', version: 1, created_at: '2026-10-04T00:00:00Z', updated_at: '2026-10-04T00:00:00Z' }
const revision = { revision_id: 'rev-1', document_id: 'doc-1', base_version: 1, action: 'rewrite' as const, before_markdown: '原文内容', after_markdown: '建议内容', status: 'pending' as const, warnings: [], created_at: doc.created_at }
function Location() { return <div data-testid="location">{useLocation().pathname}</div> }
function wrap(element: React.ReactNode) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={['/writing']}><Routes><Route path="*" element={<>{element}<Location /></>} /></Routes></MemoryRouter></QueryClientProvider>) }
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(done => { resolve = done }); return { promise, resolve } }
beforeEach(() => { vi.resetAllMocks(); sessionStorage.clear(); vi.mocked(writingApi.summary).mockResolvedValue({ sample_count: 0, genres: [], documents: [] }); vi.mocked(writingApi.samples).mockResolvedValue({ items: [] }); vi.mocked(writingApi.document).mockResolvedValue(doc); vi.mocked(writingApi.revisions).mockResolvedValue({ items: [] }); vi.mocked(writingApi.create).mockResolvedValue(doc); vi.mocked(writingApi.update).mockImplementation(async (_id, body) => ({ ...doc, ...body, version: 2 })); vi.mocked(writingApi.propose).mockResolvedValue(revision); vi.mocked(writingApi.resolve).mockResolvedValue({ document: { ...doc, markdown: '建议内容', version: 2 }, revision: { ...revision, status: 'accepted' } }); HTMLElement.prototype.scrollIntoView = vi.fn() })
afterEach(cleanup)
describe('real writing home integration', () => {
  it('renders zero real samples and no fake recent article', async () => { wrap(<WritingHomePage userId="u1" />); expect(await screen.findByText('还没有文稿。说说想写什么，或从下方新建。')).toBeInTheDocument(); expect(screen.queryByText('便利店与第三空间')).not.toBeInTheDocument(); expect(screen.getByText('0')).toBeInTheDocument() })
  it('creates a blank genre document and navigates to its returned identity', async () => { wrap(<WritingHomePage userId="u1" />); fireEvent.click(await screen.findByRole('button', { name: '空白文档' })); await waitFor(() => expect(screen.getByTestId('location')).toHaveTextContent('/writing/doc-1')); expect(writingApi.create).toHaveBeenCalledWith({ title: '未命名随笔', genre: 'essay', markdown: '' }, expect.any(String)); expect(writingApi.propose).not.toHaveBeenCalled() })
  it('locks repeated generation clicks and sends one charged operation', async () => { const pending = deferred<typeof revision>(); vi.mocked(writingApi.propose).mockReturnValue(pending.promise); wrap(<WritingHomePage userId="u1" />); fireEvent.change(screen.getByRole('textbox', { name: '写作要求' }), { target: { value: '写一个开头' } }); const send = screen.getByRole('button', { name: '发送给 Everplain' }); fireEvent.click(send); fireEvent.click(send); await waitFor(() => expect(writingApi.propose).toHaveBeenCalledTimes(1)); expect(writingApi.create).toHaveBeenCalledTimes(1); await act(async () => pending.resolve(revision)) })
  it('keeps the prompt and idempotency key after create network failure', async () => { vi.mocked(writingApi.create).mockRejectedValue(new Error('网络不可用')); wrap(<WritingHomePage userId="u1" />); fireEvent.change(screen.getByRole('textbox', { name: '写作要求' }), { target: { value: '保留我的要求' } }); fireEvent.click(screen.getByRole('button', { name: '发送给 Everplain' })); await screen.findByText('网络不可用'); expect(screen.getByRole('textbox', { name: '写作要求' })).toHaveValue('保留我的要求'); fireEvent.click(screen.getByRole('button', { name: '发送给 Everplain' })); await waitFor(() => expect(writingApi.create).toHaveBeenCalledTimes(2)); expect(vi.mocked(writingApi.create).mock.calls[0][1]).toBe(vi.mocked(writingApi.create).mock.calls[1][1]) })
  it('does not fetch another owner data while unauthenticated', async () => { wrap(<WritingHomePage userId={null} />); await act(async () => {}); expect(writingApi.summary).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: '空白文档' })); expect(writingApi.create).not.toHaveBeenCalled() })
  it('shows fetch failure rather than substituting example content', async () => { vi.mocked(writingApi.summary).mockRejectedValue(new Error('读取失败')); wrap(<WritingHomePage userId="u1" />); expect(await screen.findByRole('alert')).toHaveTextContent('读取失败'); expect(screen.queryByText('28')).not.toBeInTheDocument() })
})
describe('sample import preview and confirmation', () => {
  const item = { title: '合成随笔', text: '雨停之后，我沿着河岸慢慢走回去。'.repeat(10), character_count: 180, excluded_reason: null }
  const saved = { sample_id: 's1', title: item.title, genre: 'essay' as const, character_count: 180, created_at: doc.created_at }
  function chooseFile() { fireEvent.change(document.querySelector('input[type="file"]')!, { target: { files: [new File(['synthetic'], '合集.txt', { type: 'text/plain' })] } }) }
  beforeEach(() => { vi.mocked(writingApi.previewSamples).mockResolvedValue({ items: [item, { ...item, title: '删去的', excluded_reason: '原文标记为删去或弃稿，默认不导入。' }], warnings: ['预览不会保存样文或调用模型。'] }); vi.mocked(writingApi.createSample).mockResolvedValue(saved) })
  it('previews without saving and requires a genre for each included piece', async () => { wrap(<WritingHomePage userId="u1" />); chooseFile(); await screen.findByRole('region', { name: '样文导入预览' }); expect(writingApi.upload).not.toHaveBeenCalled(); expect(writingApi.createSample).not.toHaveBeenCalled(); expect(screen.getByRole('checkbox', { name: '导入文章 2' })).not.toBeChecked(); fireEvent.click(screen.getByRole('button', { name: '确认导入选中文章' })); expect(await screen.findByRole('alert')).toHaveTextContent('确认文体'); expect(writingApi.createSample).not.toHaveBeenCalled(); fireEvent.change(screen.getByRole('combobox', { name: '样文文体 1' }), { target: { value: 'essay' } }); fireEvent.click(screen.getByRole('button', { name: '确认导入选中文章' })); await waitFor(() => expect(writingApi.createSample).toHaveBeenCalledTimes(1)); expect(writingApi.createSample).toHaveBeenCalledWith({ title: item.title, genre: 'essay', text: item.text }, expect.any(String)) })
  it('cancels a preview without persisting samples', async () => { wrap(<WritingHomePage userId="u1" />); chooseFile(); await screen.findByRole('region', { name: '样文导入预览' }); fireEvent.click(screen.getByRole('button', { name: '取消导入' })); expect(screen.queryByRole('region', { name: '样文导入预览' })).not.toBeInTheDocument(); expect(writingApi.createSample).not.toHaveBeenCalled() })
  it('cancels an in-flight parser and ignores its late result', async () => { const pending = deferred<Awaited<ReturnType<typeof writingApi.previewSamples>>>(); vi.mocked(writingApi.previewSamples).mockReturnValue(pending.promise); wrap(<WritingHomePage userId="u1" />); chooseFile(); fireEvent.click(await screen.findByRole('button', { name: '取消解析' })); await act(async () => pending.resolve({ items: [item], warnings: [] })); expect(screen.queryByRole('region', { name: '样文导入预览' })).not.toBeInTheDocument(); expect(writingApi.createSample).not.toHaveBeenCalled(); expect(vi.mocked(writingApi.previewSamples).mock.calls[0][1]?.aborted).toBe(true) })
  it('serializes confirmations and retries only unsaved pieces with stable keys', async () => { vi.mocked(writingApi.previewSamples).mockResolvedValue({ items: [item, { ...item, title: '第二篇' }], warnings: [] }); vi.mocked(writingApi.createSample).mockResolvedValueOnce(saved).mockRejectedValueOnce(new Error('网络中断')).mockResolvedValue(saved); wrap(<WritingHomePage userId="u1" />); chooseFile(); await screen.findByRole('region', { name: '样文导入预览' }); for (const index of [1, 2]) fireEvent.change(screen.getByRole('combobox', { name: `样文文体 ${index}` }), { target: { value: 'essay' } }); const confirm = screen.getByRole('button', { name: '确认导入选中文章' }); fireEvent.click(confirm); fireEvent.click(confirm); await screen.findByText(/网络中断/); expect(writingApi.createSample).toHaveBeenCalledTimes(2); fireEvent.click(confirm); await waitFor(() => expect(writingApi.createSample).toHaveBeenCalledTimes(3)); const calls = vi.mocked(writingApi.createSample).mock.calls; expect(calls[1][1]).toBe(calls[2][1]); expect(calls[2][0].title).toBe('第二篇') })
  it('splits only at an author-selected paragraph and asks the new piece genre', async () => { vi.mocked(writingApi.previewSamples).mockResolvedValue({ items: [{ ...item, text: `${item.text}\n\n${item.text}` }], warnings: [] }); wrap(<WritingHomePage userId="u1" />); chooseFile(); fireEvent.click(await screen.findByRole('button', { name: '拆成独立文章' })); expect(screen.getByRole('textbox', { name: '样文正文 2' })).toHaveValue(item.text); expect(screen.getByRole('combobox', { name: '样文文体 2' })).toHaveValue(''); expect(writingApi.createSample).not.toHaveBeenCalled() })
})
describe('writing draft and revision safety', () => {
  it('saves exact Markdown and requires current expected_version', async () => { wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); const input = await screen.findByRole('textbox', { name: 'Markdown 源码' }); const markdown = '---\ntitle: old\n---\n\n[[双链|别名]]\n```js\nlet a=1\n```\n'; fireEvent.change(input, { target: { value: markdown } }); fireEvent.click(screen.getByRole('button', { name: '保存' })); await waitFor(() => expect(writingApi.update).toHaveBeenCalledWith('doc-1', expect.objectContaining({ markdown, expected_version: 1 }), expect.any(String))) })
  it('restores only the current owner’s draft after refresh', async () => { sessionStorage.setItem(draftKey('u1', 'doc-1'), JSON.stringify({ title: '恢复标题', genre: 'essay', markdown: '未保存全文', version: 1 })); sessionStorage.setItem(draftKey('u2', 'doc-1'), JSON.stringify({ title: '他人标题', genre: 'essay', markdown: '他人全文', version: 1 })); wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); expect(await screen.findByRole('textbox', { name: 'Markdown 源码' })).toHaveValue('未保存全文'); expect(screen.getByRole('textbox', { name: '文稿标题' })).toHaveValue('恢复标题'); expect(screen.queryByText('他人全文')).not.toBeInTheDocument() })
  it('leaves unsaved body intact on failed save and reuses attempt key', async () => { vi.mocked(writingApi.update).mockRejectedValue(new Error('版本冲突')); wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); fireEvent.change(await screen.findByRole('textbox', { name: 'Markdown 源码' }), { target: { value: '本地修改' } }); fireEvent.click(screen.getByRole('button', { name: '保存' })); await screen.findByText('版本冲突'); expect(screen.getByRole('textbox', { name: 'Markdown 源码' })).toHaveValue('本地修改'); fireEvent.click(screen.getByRole('button', { name: '保存' })); await waitFor(() => expect(writingApi.update).toHaveBeenCalledTimes(2)); expect(vi.mocked(writingApi.update).mock.calls[0][2]).toBe(vi.mocked(writingApi.update).mock.calls[1][2]) })
  it('never replaces original body just because a proposal returned', async () => { wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); fireEvent.click(await screen.findByRole('button', { name: '改写全文' })); await screen.findByText('建议内容'); expect(screen.getByRole('textbox', { name: 'Markdown 源码' })).toHaveValue('原文内容'); expect(writingApi.resolve).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: '接受' })); await waitFor(() => expect(screen.getByRole('textbox', { name: 'Markdown 源码' })).toHaveValue('建议内容')); expect(writingApi.resolve).toHaveBeenCalledWith('doc-1', 'rev-1', { decision: 'accept', expected_version: 1 }, expect.any(String)) })
  it('blocks acceptance over an unsaved user edit', async () => { vi.mocked(writingApi.revisions).mockResolvedValue({ items: [revision] }); wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); fireEvent.change(await screen.findByRole('textbox', { name: 'Markdown 源码' }), { target: { value: '新手写内容' } }); fireEvent.click(screen.getByRole('tab', { name: '修订 · 1' })); expect(screen.getByRole('button', { name: '接受' })).toBeDisabled(); expect(writingApi.resolve).not.toHaveBeenCalled() })
  it('keeps draft and budget error when generation is rejected', async () => { vi.mocked(writingApi.propose).mockRejectedValue(new Error('积分不足')); wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); fireEvent.click(await screen.findByRole('button', { name: '更像我' })); await screen.findByText('积分不足'); expect(screen.getByRole('textbox', { name: 'Markdown 源码' })).toHaveValue('原文内容'); expect(writingApi.propose).toHaveBeenCalledTimes(1) })
  it('makes no automatic model call during document open or Agent-tab open', async () => { wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); await screen.findByRole('textbox', { name: 'Markdown 源码' }); fireEvent.click(screen.getByRole('tab', { name: 'Agent' })); expect(screen.getByText('公共 Agent 面板')).toBeInTheDocument(); expect(writingApi.propose).not.toHaveBeenCalled() })
  it('serializes duplicate save clicks', async () => { const pending = deferred<typeof doc>(); vi.mocked(writingApi.update).mockReturnValue(pending.promise); wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); fireEvent.change(await screen.findByRole('textbox', { name: '文稿标题' }), { target: { value: '新题' } }); const save = screen.getByRole('button', { name: '保存' }); fireEvent.click(save); fireEvent.click(save); expect(writingApi.update).toHaveBeenCalledTimes(1); await act(async () => pending.resolve({ ...doc, title: '新题' })) })
  it('refreshes server version while preserving conflicted local edits', async () => { vi.mocked(writingApi.update).mockRejectedValue(new Error('版本冲突')); wrap(<WritingDocumentEditor userId="u1" documentId="doc-1" />); fireEvent.change(await screen.findByRole('textbox', { name: 'Markdown 源码' }), { target: { value: '本地内容' } }); fireEvent.click(screen.getByRole('button', { name: '保存' })); await screen.findByText('版本冲突'); vi.mocked(writingApi.document).mockResolvedValue({ ...doc, version: 5, markdown: '服务器新正文' }); fireEvent.click(screen.getByRole('button', { name: '刷新版本并保留修改' })); await screen.findByText('服务器版本已刷新，本地修改仍保留。请对照最新正文后再保存。'); expect(screen.getByRole('textbox', { name: 'Markdown 源码' })).toHaveValue('本地内容') })
})
