"""Compile shared canonical SVG geometry to native Compose ImageVectors."""
import json, pathlib, hashlib
root=pathlib.Path(__file__).resolve().parent
source=root.parent/'tokens/assets/icons/icons.json'
d=json.loads(source.read_text())
extra=root/'verification/extra-phosphor-2.1.10.json'
if extra.exists(): d['phosphor'].update(json.loads(extra.read_text())['icons'])
header='''// Generated by android/generate_icons.py from shared canonical Web assets.
// Do not substitute navigation strokes with similarly named Phosphor icons.
package app.everplain.android

import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

'''
def path(node):
 a=node['attributes'];t=node['type']
 if t=='path': return a['d']
 if t=='circle':
  x,y,r=map(float,(a['cx'],a['cy'],a['r']))
  return f'M{x-r} {y}a{r} {r} 0 1 0 {2*r} 0a{r} {r} 0 1 0 {-2*r} 0Z'
 if t=='rect':
  x,y,w,h=[float(a.get(k,0)) for k in ('x','y','width','height')];r=min(float(a.get('rx',0)),w/2,h/2)
  if not r:return f'M{x} {y}h{w}v{h}h{-w}Z'
  return f'M{x+r} {y}h{w-2*r}a{r} {r} 0 0 1 {r} {r}v{h-2*r}a{r} {r} 0 0 1 {-r} {r}h{-w+2*r}a{r} {r} 0 0 1 {-r} {-r}v{-h+2*r}a{r} {r} 0 0 1 {r} {-r}Z'
 raise ValueError(t)
alias={'List':'Menu','Plus':'Add','ArrowUp':'ArrowUpward','Copy':'ContentCopy','X':'Close','CaretDown':'ExpandMore','CaretRight':'ChevronRight','NotePencil':'EditNote','DotsThree':'MoreHoriz','House':'Home','User':'Person','SlidersHorizontal':'Tune','ArrowClockwise':'Refresh'}
for group,obj in [('phosphor','EpIcons'),('navigation','NavIcons')]:
 text=header+f'// Shared asset SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}\nobject {obj} {{\n'
 for name,icon in d[group].items():
  name=alias.get(name,name) if group=='phosphor' else name[0].upper()+name[1:]
  text+=f'    val {name}: ImageVector by lazy {{\n        ImageVector.Builder("{obj}.{name}", 24.dp, 24.dp, {icon["viewBox"][2]}f, {icon["viewBox"][3]}f).apply {{\n'
  for node in icon['nodes']:
   geom=json.dumps(path(node))
   paint='fill = SolidColor(Color.Black)' if group=='phosphor' else 'fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 1.75f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round'
   text+=f'            addPath(PathParser().parsePathString({geom}).toNodes(), {paint})\n'
  text+='        }.build()\n    }\n'
 # Historical local name maps to same verified ArrowClockwise source.
 if group=='phosphor': text+='    val History: ImageVector get() = Refresh\n'
 text+='}\n'
 (root/f'app/src/main/java/app/everplain/android/{obj}.kt').write_text(text)
