import { File as NodeFile } from 'node:buffer'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { writingApi } from './writingApi'
afterEach(() => vi.unstubAllGlobals())
function respond(body: unknown, status = 200) { const requests: Request[] = []; vi.stubGlobal('fetch', vi.fn(async (request: Request) => { requests.push(request); return new Response(status === 204 ? null : JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }) })); return requests }
describe('writingApi owner-bound generated contract', () => {
  it('previews multipart content without assigning a genre or creating a sample', async () => { const calls = respond({ items: [], warnings: [] }); const controller = new AbortController(); await writingApi.previewSamples(new NodeFile(['synthetic'], 'sample.txt', { type: 'text/plain' }) as unknown as File, controller.signal); expect(new URL(calls[0].url).pathname).toBe('/api/writing/samples/preview'); const form = await calls[0].formData(); expect(form.has('genre')).toBe(false); expect(calls[0].credentials).toBe('include'); expect(calls).toHaveLength(1) })
  it('creates only the confirmed article through the existing sample endpoint', async () => { const calls = respond({}); const body = { title: '确认的文章', genre: 'essay' as const, text: '合成正文'.repeat(30) }; await writingApi.createSample(body, 'stable-import'); expect(new URL(calls[0].url).pathname).toBe('/api/writing/samples'); expect(await calls[0].json()).toEqual(body); expect(calls[0].headers.get('Idempotency-Key')).toBe('stable-import') })
  it('uses session cookies and idempotency, without accepting an owner or billing override', async () => { const calls = respond({ document_id: 'doc', version: 1 }); await writingApi.create({ title: '标题', genre: 'essay', markdown: '正文' }, 'test-key'); expect(calls[0].credentials).toBe('include'); expect(calls[0].headers.get('Idempotency-Key')).toBe('test-key'); expect(calls[0].headers.get('Authorization')).toBeNull(); expect(await calls[0].json()).toEqual({ title: '标题', genre: 'essay', markdown: '正文' }); expect(new URL(calls[0].url).pathname).toBe('/api/writing/documents') })
  it('retains exact markdown and expected version when saving', async () => { const calls = respond({}); const markdown = '---\ntitle: a\n---\n\n[[笔记|别名]]\n==高亮==\n'; await writingApi.update('doc', { expected_version: 3, markdown }, 'same-attempt'); expect(await calls[0].json()).toEqual({ expected_version: 3, markdown }); expect(calls[0].method).toBe('PATCH') })
  it('transmits bounded instruction/UTF-16 selection once, with no invented model cost', async () => { const calls = respond({}); await writingApi.propose('doc', { action: 'personalize', instruction: '保留事实', expected_version: 3, selection_start: 2, selection_end: 5 }, 'generation-attempt'); expect(await calls[0].json()).toEqual({ action: 'personalize', instruction: '保留事实', expected_version: 3, selection_start: 2, selection_end: 5 }); expect(calls).toHaveLength(1) })
  it('preserves safe billing failure details and status without auto retry', async () => { const calls = respond({ error: { code: 'insufficient_credits', message: '积分不足，请先补充积分。' } }, 402); await expect(writingApi.propose('doc', { action: 'continue', expected_version: 1 }, 'attempt')).rejects.toMatchObject({ message: '积分不足，请先补充积分。', status: 402 }); expect(calls).toHaveLength(1) })
  it('does not surface arbitrary provider detail', async () => { respond({ detail: 'secret upstream URL' }, 500); await expect(writingApi.summary()).rejects.toThrow('写作请求未完成'); try { await writingApi.summary() } catch (e) { expect(String(e)).not.toContain('secret') } })
  it('propagates 401 as session failure', async () => { respond({}, 401); await expect(writingApi.document('doc')).rejects.toMatchObject({ name: 'ApiRequestError', status: 401 }) })
  it('sends exact accept decision and current version', async () => { const calls = respond({}); await writingApi.resolve('doc', 'rev', { decision: 'accept', expected_version: 2 }, 'decision-attempt'); expect(new URL(calls[0].url).pathname).toBe('/api/writing/documents/doc/revisions/rev/resolve'); expect(await calls[0].json()).toEqual({ decision: 'accept', expected_version: 2 }) })
  it('uses multipart upload and preserves requested genre', async () => { const calls = respond({}); await writingApi.upload(new NodeFile(['样文'.repeat(100)], 'sample.txt', { type: 'text/plain' }) as unknown as File, 'report', 'upload-key'); const form = await calls[0].formData(); expect(form.get('genre')).toBe('report'); expect(calls[0].headers.get('Content-Type')).toContain('multipart/form-data'); expect(calls[0].headers.get('Idempotency-Key')).toBe('upload-key') })
  it('accepts 204 deletion and targets one owner-scoped sample', async () => { const calls = respond(null, 204); await writingApi.deleteSample('sample'); expect(calls[0].method).toBe('DELETE'); expect(new URL(calls[0].url).pathname).toBe('/api/writing/samples/sample') })
})
