// Static bilingual UI pairs captured from the actual Web source text(zh, en) calls.
// User content is never passed through this table by its callers.
#if os(macOS)
import SwiftUI

enum EPInterfaceStrings {
    static let english: [String: String] = [
        "严谨细致": "Careful & thorough",
        "个人资料": "Profile",
        "今晚我值班。": "I am on duty tonight.",
        "你回来啦。": "There you are again.",
        "使用偏好": "Preferences",
        "偷得浮生半日闲。": "A little pause in a busy day.",
        "别来无恙。": "Good to see you again.",
        "夜猫子，集合。": "Night owls, assemble.",
        "太阳已到岗。": "The sun has clocked in.",
        "好奇开放": "Curious & open",
        "安全": "Security",
        "恭候多时。": "At your service.",
        "我的 Agent": "My Agent",
        "数据与隐私": "Data & privacy",
        "新密码": "New password",
        "月亮值班中。": "The moon is on duty.",
        "来啦。": "Oh, hello.",
        "清晰直接": "Clear & direct",
        "温和自然": "Warm & natural",
        "确认新密码": "Confirm new password",
        "聊天平台": "Chat platforms",
        "账户状态": "Account status",
        "这么巧，你也在。": "Fancy meeting you here.",

        "AI 伙伴": "AI companion",
        "Agent 对话": "Agent conversation",
        "Agent 对话记录": "Agent conversation history",
        "Agent 工作过程": "Agent activity",
        "Agent 已完成工具调用": "Agent completed its tool activity",
        "Agent 开始检索后，这里按步骤记录它做了什么。": "Steps appear here once the Agent starts retrieving.",
        "Agent 正在调用工具": "Agent is using tools",
        "Agent 预览": "Agent preview",
        "Everplain": "Everplain",
        "Everplain Agent 对话": "Everplain conversation",
        "Everplain 功能栏": "Everplain navigation",
        "Everplain 官网": "Everplain website",
        "Everplain 当前不使用你的数据训练模型。开启仅记录未来可选改进计划的授权；任何实际启用仍会另行告知。": "Everplain does not currently train on your data. Enabling this only records consent for a future optional improvement program; you will be notified before any actual use.",
        "Memory · 记忆": "Memory",
        "Soul · 人格": "Soul",
        "一次性绑定命令": "One-time binding command",
        "上一页": "Previous",
        "上一页用量记录": "Previous usage page",
        "上传": "Upload",
        "上传文件": "Upload a file",
        "下一步": "Next step",
        "下一步：": "Next: ",
        "下一页": "Next",
        "下一页用量记录": "Next usage page",
        "下载 PDF": "Download PDF",
        "下载 Word": "Download Word",
        "下载数据副本": "Download data copy",
        "不可用": "Unavailable",
        "不限量": "Unlimited",
        "与": " and ",
        "两次输入的新密码不一致。": "The new passwords do not match.",
        "个人账户": "Personal account",
        "中国标准时间": "China Standard Time",
        "为你整理知识，一起探索想法": "Organize knowledge and explore ideas together",
        "事实、假设与核查清单": "Facts, assumptions and checks",
        "人格描述最多 8000 个字符。": "Soul description allows up to 8000 characters.",
        "人格描述（Markdown）": "Soul description (Markdown)",
        "从一个问题或一份资料开始。研究进度、依据和下一步会保存在这里。": "Start with a question or a document. Stages, evidence, and next steps will be saved here.",
        "从研究材料添加": "Add from research materials",
        "付款逾期": "Payment overdue",
        "伙伴设置": "Companion settings",
        "会话已撤销。": "Session revoked.",
        "作废绑定码": "Cancel code",
        "你的研究内容没有丢失，可以重新请求列表。": "Your research is safe. You can request the list again.",
        "你的研究材料": "Your materials",
        "你的账户与研究数据没有改变。请检查网络后重试。": "Your account and research data are unchanged. Check your connection and try again.",
        "使用情况": "Usage",
        "使用额度": "Allowance",
        "例如：你是我的阅读伙伴。先听我说完，再提出不同解释；有疑问时坦诚说明。": "For example: Be my reading companion. Listen first, offer alternative explanations, and be honest about uncertainty.",
        "依据": "Basis",
        "保存": "Save",
        "保存 Agent": "Save Agent",
        "保存偏好": "Save preferences",
        "保存对话名称": "Save conversation name",
        "保存角色": "Save identity",
        "保存资料": "Save profile",
        "保留我的修改继续编辑": "Keep my edits and continue",
        "修改": "Edit",
        "修改名称": "Rename",
        "修改对话名称": "Rename conversation",
        "修改显示名称": "Edit display name",
        "偏好已保存。": "Preferences saved.",
        "停止后，未来可选改进计划不再取得你的授权；研究功能所需推理不受影响。": "Future optional improvement programs will no longer have your consent. Inference required for research features is unaffected.",
        "停止用于改进模型？": "Stop model improvement access?",
        "停用": "Deactivate",
        "停用原因": "Reason for deactivation",
        "停用后你会立即退出所有设备。数据会保留，管理员可在核验后恢复访问。": "You will be signed out on every device. Your data is retained, and an administrator can restore access after verification.",
        "停用账户": "Deactivate account",
        "停用账户？": "Deactivate account?",
        "允许用于改进模型": "Allow model improvement",
        "允许用于改进模型？": "Allow model improvement?",
        "兑换": "Redeem",
        "兑换成功。": "Code redeemed.",
        "兑换码": "Redemption code",
        "兑换码到账": "Code redemption",
        "全部": "All",
        "公开网页": "Public web",
        "共享": "Sharing",
        "关闭上下文栏": "Close context panel",
        "关闭后保留草稿": "Draft stays when closed",
        "关闭深入研究介绍": "Close deep research introduction",
        "关闭研究记录": "Close research history",
        "关闭研究面板": "Close research panel",
        "关闭菜单": "Close menu",
        "关闭角色面板": "Close companion panel",
        "关闭账户设置": "Close account settings",
        "关闭通知": "Close notifications",
        "关闭错误提示": "Close error message",
        "准备研究产出": "Shape the deliverable",
        "切换项目": "Switch project",
        "创建": "Create",
        "创建中…": "Creating…",
        "创建项目": "Create project",
        "删除": "Delete",
        "删除中…": "Deleting…",
        "删除后，任务及其派生内容无法恢复。": "The task and its derived content cannot be recovered after deletion.",
        "删除失败，研究内容仍然保留。": "Deletion failed. Your research is still available.",
        "删除对话": "Delete conversation",
        "删除研究": "Delete research",
        "删除这段对话？": "Delete this conversation?",
        "删除项目": "Delete project",
        "制定查证计划": "Plan the investigation",
        "刷新状态": "Refresh status",
        "剩余使用额度": "Remaining allowance",
        "加入时间": "Joined",
        "包含账户资料、研究任务与模型交互记录，不包含密码或会话凭据。": "Includes your profile, research tasks, and model interactions. Excludes passwords and session credentials.",
        "升级套餐": "Upgrade plan",
        "协调世界时": "Coordinated Universal Time",
        "去新建研究": "Open new research",
        "发现": "Discover",
        "取消": "Cancel",
        "取消修改": "Cancel edits",
        "变更请联系管理员": "Contact an administrator to change",
        "另一处已保存了新版本。你的草稿仍在编辑框内，先核对下面的最新档案。": "A new version was saved elsewhere. Your draft remains in the editor; review the latest profile below.",
        "只把标题当作主题线索，不假定已读过其他对话或材料；背景不足时先问我。": "Use this title only as a topic cue. Do not assume access to other conversations or materials; ask me for missing context first.",
        "名字": "Name",
        "名字需要 1–40 个字符。": "Use a name between 1 and 40 characters.",
        "命令已复制。只发送给你选择的机器人私聊。": "Command copied. Send it only to your selected bot in a private chat.",
        "回答完成后，来源会出现在这里": "Sources will appear here when the answer is complete",
        "回答证据": "Answer evidence",
        "围绕你的研究项目": "For your research project",
        "围绕最近的对话主题": "From your recent conversation topic",
        "图谱": "Graph",
        "在机器人私聊发送这条命令": "Send this command in the bot’s private chat",
        "在知识图谱中查看": "View in knowledge graph",
        "在飞书或 Telegram 私聊中使用你的 Everplain Agent。群聊和附件暂未开放。": "Use your Everplain Agent in Feishu or Telegram private chats. Groups and attachments are not supported yet.",
        "基于已附加材料": "From your attached materials",
        "处理中": "Pending",
        "处理中…": "Working…",
        "复制命令": "Copy command",
        "复制回答": "Copy answer",
        "复制失败": "Copy failed",
        "外观": "Appearance",
        "失败": "Failed",
        "套餐信息待确认": "Plan not identified",
        "套餐信息暂不可用": "Plan unavailable",
        "套餐额度": "Plan allowance",
        "存为笔记": "Save as note",
        "完成": "Completed",
        "完成首轮对话后，用量流水会出现在这里。": "Usage will appear here after your first conversation.",
        "实际工具步骤会出现在这里。": "Actual tool steps will appear here.",
        "对话与研究": "Conversations and research",
        "对话所属项目": "Conversation project",
        "对话操作": "Conversation actions",
        "对话视图": "Conversation view",
        "对话记录暂时无法加载，但你仍然可以开始新对话。": "Conversation history is unavailable, but you can still start a new conversation.",
        "对话设置": "Conversation settings",
        "导入": "Imports",
        "导出": "Export",
        "导出我的数据": "Export my data",
        "展开侧栏": "Expand sidebar",
        "展开对话与研究": "Show conversations and research",
        "工作流程": "Workflow",
        "工作空间入口": "Workspace destinations",
        "工具活动": "Tool activity",
        "工具结果数据": "Tool result data",
        "工具调用已中断": "Tool activity was interrupted",
        "工具调用未完成": "Tool activity did not complete",
        "工具输入": "Tool input",
        "已中断": "Interrupted",
        "已保存": "Saved",
        "已删除": "Deleted",
        "已取消": "Canceled",
        "已复制": "Copied",
        "已完成": "Completed",
        "已暂停": "Paused",
        "已检索个人材料，但没有可展示的原文位置，请谨慎引用。": "Personal materials were searched, but no displayable source position was returned. Cite with care.",
        "已检索知识库，但没有可展示的来源，请谨慎引用。": "The knowledge base was searched, but no displayable source was returned. Cite with care.",
        "已添加": "Added",
        "已确认绑定成功，可以去平台私聊了。": "Binding confirmed. You can now chat privately on the platform.",
        "已绑定账号": "Linked accounts",
        "已结算": "Settled",
        "已解除绑定，尚未发送的私人回复将停止投递。": "Binding revoked. Pending private replies will be stopped.",
        "已过期": "Expired",
        "已退款": "Refunded",
        "平台账号": "Platform account",
        "开始新对话": "Start a new conversation",
        "开始深入研究": "Start deep research",
        "开始第一项研究": "Start your first study",
        "引用位置：": "Source location: ",
        "引用来源": "Citation source",
        "当 Agent 需要检索或整理证据时，过程会显示在这里。": "When the Agent retrieves or organizes evidence, the process will appear here.",
        "当前会话": "Current session",
        "当前回合的知识版本尚未确认，暂不提供跳转。": "The knowledge release for this turn has not been confirmed; navigation is unavailable.",
        "当前回合进行中，结束后可调整。": "You can change this after the current turn finishes.",
        "当前密码": "Current password",
        "当前是隔离测试模型。": "This is the isolated test runtime.",
        "当前设备不会退出。": "Your current device stays signed in.",
        "当前项目": "Current project",
        "当本次回答绑定知识库来源时，来源会和回答保持对应。": "Knowledge sources stay linked to the answer that used them.",
        "形成研究提纲": "Build a report outline",
        "待完成付款": "Payment pending",
        "思考强度": "Reasoning effort",
        "恢复中的回合沿用原模型和强度，当前不可修改。": "The resumed turn keeps its original model and effort.",
        "我想讨论的主题": "the topic I want to discuss",
        "我理解私聊可能使用我的个人记忆与有权限的资料，回答会发送到所选平台，并按现有 Everplain 用量计费。": "I understand private chats may use my personal memory and authorized sources, send answers to the selected platform, and count toward my existing Everplain usage.",
        "我的 AI 伙伴": "My AI companion",
        "我的账户": "My account",
        "所选模型暂时不可用。问题已保留，请选择模型后重试。": "The selected model is unavailable. Your question is saved; choose a model and retry.",
        "打开原文位置": "Open source location",
        "打开对话操作": "Open conversation actions",
        "打开机器人私聊": "Open bot private chat",
        "打开用户管理": "Open user management",
        "打开知识条目": "Open knowledge entry",
        "打开研究记录": "Open research history",
        "打开网页": "Open web page",
        "打开菜单": "Open menu",
        "找出证据缺口": "Find evidence gaps",
        "把想法写清楚": "Put an idea into words",
        "报告框架与待补充证据": "Report outline and missing evidence",
        "按实际调用计算用量，失败或中止的回答不消耗额度。": "Based on actual usage. Failed or interrupted responses do not consume your allowance.",
        "描述你想弄清楚的问题": "Describe what you want to investigate",
        "提出问题，让研究从材料开始推进": "Ask a question and move research forward from evidence",
        "提炼关键证据": "Extract the evidence",
        "搜索研究记录": "Search research history",
        "搜索问题或项目": "Search questions or projects",
        "搜索项目": "Search projects",
        "撤销": "Revoke",
        "撤销其他设备的会话": "Sign out other devices",
        "撤销这个会话？": "Revoke this session?",
        "操作": "Actions",
        "操作失败，请重试。": "The operation failed. Please try again.",
        "操作未完成，已保留当前数据。请检查网络后重试。": "The change was not completed. Your current data is unchanged. Check your connection and try again.",
        "操作结果尚未确认。请刷新绑定状态后再操作。": "The result is not confirmed. Refresh binding status before trying again.",
        "收益、代价与选择依据": "Benefits, costs and decision criteria",
        "收起侧栏": "Collapse sidebar",
        "收起对话与研究": "Hide conversations and research",
        "放弃当前未保存的修改，恢复已保存的档案？": "Discard unsaved edits and restore the saved profile?",
        "放弃未保存的修改": "Discard unsaved edits",
        "放进研究": "Add to research",
        "数据副本已准备。": "Your data copy is ready.",
        "数据副本正在准备，请稍后重新查看。": "Your data copy is being prepared. Check again later.",
        "整理自己的资料，随时检索并回到原文": "Organize your sources, find answers, and trace them back to the original",
        "新侧栏布局": "New sidebar layout",
        "新密码需要 12-128 个字符。": "New password must be between 12 and 128 characters.",
        "新对话": "New conversation",
        "新建对话": "New conversation",
        "新建研究": "New research",
        "新建项目": "New project",
        "新用户赠送": "Welcome allowance",
        "时区": "Time zone",
        "时间未知": "Unknown time",
        "明确读者和目的，整理重点与结构": "Audience, purpose, key points and structure",
        "显示名称": "Display name",
        "显示名称需要 1-80 个字符。": "Display name must be between 1 and 80 characters.",
        "暂不可用": "Unavailable",
        "暂停待重试": "Pause needs retry",
        "暂停未被服务端确认，请重试暂停。": "The server has not confirmed the pause. Try again.",
        "暂无新消息": "No new messages",
        "暂时无法保存，请重试。": "Could not save. Please try again.",
        "暂时无法读取 Agent 设置。": "Could not load Agent settings.",
        "暂时无法读取最近研究": "Recent research is unavailable",
        "暂时无法读取研究任务": "Research tasks are unavailable",
        "暂时无法读取聊天平台，请重试。": "Chat platforms could not be loaded. Try again.",
        "暂时无法读取角色身份。": "Could not load your companion.",
        "暂时无法读取账户设置": "Account settings are unavailable",
        "更多功能": "More features",
        "更多对话操作": "More conversation actions",
        "更多自定义": "Add your own",
        "更新于": "Updated",
        "更新密码": "Update password",
        "更新日志": "Updates",
        "更新时间": "Updated",
        "最新人格描述": "Latest Soul description",
        "最新身份与风格": "Latest identity and style",
        "最近对话": "Recent conversations",
        "最近更新": "Recently updated",
        "最近活动": "Last active",
        "最近研究": "Recent research",
        "有效至": "Valid until",
        "未付款": "Unpaid",
        "未填写": "Empty",
        "未归属项目的对话会显示在这里": "Conversations without a project appear here",
        "未能写入剪贴板，请手动选中并复制下面的命令。": "Clipboard access failed. Select and copy the command below.",
        "未订阅": "No subscription",
        "本轮 Agent 没有返回可展开的证据摘录。": "The Agent returned no expandable evidence excerpt for this turn.",
        "本轮已停止，未保存未完成的回答。": "This turn stopped before an unfinished answer was saved.",
        "本轮引用": "Cited this turn",
        "本轮暂无来源。": "No sources for this turn yet.",
        "本轮没有可摘录的结论，完整回答见对话正文。": "No excerpted conclusion was returned; see the full answer in the conversation.",
        "本轮沿用原设置": "Original turn settings",
        "本轮沿用服务端默认设置，结束后可调整。": "This turn uses server defaults. You can change this after it finishes.",
        "本轮证据来源": "Evidence sources for this answer",
        "材料库": "Materials",
        "查找资料": "Finding sources",
        "查看完整工具返回": "View full tool output",
        "查看材料库": "Open material library",
        "查看活动": "View activity",
        "查看知识节点": "View knowledge node",
        "查看这一步": "View this step",
        "桌面主导航": "Main navigation",
        "档案已更新，请先查看最新版本。草稿已保留。": "Profile changed. Review the latest version; your draft is retained.",
        "检索你的资料与网页，核对来源，整理成有依据的研究结果。": "Search your materials and the web, check sources, and develop a grounded research result.",
        "检索词、来源与可靠性标准": "Search terms, sources and reliability criteria",
        "模型": "Model",
        "模型与思考强度": "Model and reasoning effort",
        "模型改进": "Model improvement",
        "模型数据授权已关闭。": "Model improvement consent disabled.",
        "模型数据授权已开启。": "Model improvement consent enabled.",
        "模型暂不可用 · 服务端默认": "Models unavailable · Server default",
        "模型未启用 · 服务端默认": "Models not enabled · Server default",
        "模型设置": "Model settings",
        "模型设置暂时无法读取，本轮使用服务端默认设置。": "Model settings could not be loaded. This turn uses server defaults.",
        "模型选择尚未启用，本轮使用服务端默认设置。": "Model selection is not enabled. This turn uses server defaults.",
        "正在作废…": "Cancelling…",
        "正在保存…": "Saving…",
        "正在停用…": "Deactivating…",
        "正在兑换…": "Redeeming…",
        "正在准备…": "Preparing…",
        "正在删除…": "Deleting…",
        "正在加载记录…": "Loading history…",
        "正在回复": "Writing",
        "正在处理…": "Updating…",
        "正在思考": "Thinking",
        "正在撤销…": "Revoking…",
        "正在整理研究框架": "Preparing the research framework",
        "正在暂停": "Pausing",
        "正在更新…": "Updating…",
        "正在更新研究进度": "Updating research progress",
        "正在根据你的选择继续讨论。": "Continuing from your selection.",
        "正在检索个人材料": "Searching personal research materials",
        "正在检索知识库": "Searching the knowledge base",
        "正在比较理论视角": "Comparing theoretical perspectives",
        "正在理解并整理研究问题": "Understanding and structuring the research question",
        "正在生成 PDF…": "Generating PDF…",
        "正在生成 Word…": "Generating Word…",
        "正在生成…": "Generating…",
        "正在生成回答": "Writing the answer",
        "正在解除…": "Unlinking…",
        "正在读取": "Loading",
        "正在读取 Agent 设置…": "Loading Agent settings…",
        "正在读取…": "Loading…",
        "正在读取可用模型；本轮仍可使用服务端默认设置。": "Loading available models. You can still use server defaults.",
        "正在读取套餐…": "Loading plan…",
        "正在读取最近研究": "Loading recent research",
        "正在读取模型": "Loading models",
        "正在读取研究任务": "Loading research tasks",
        "正在读取聊天平台…": "Loading chat platforms…",
        "正在读取角色身份…": "Loading your companion…",
        "正在读取账户设置": "Loading account settings",
        "正在重新加载": "Reloading…",
        "正在重试…": "Retrying…",
        "正在阅读研究材料": "Reading research materials",
        "此账户不能被降级、停用或删除。仍可更新密码与撤销其他会话。": "This account cannot be demoted, deactivated, or deleted. You can still update its password and revoke sessions.",
        "此页会自动确认绑定状态。关闭页面只隐藏命令；需要立即失效时，请点“作废绑定码”。": "This page checks binding status automatically. Closing it only hides the command; use “Cancel code” to invalidate it immediately.",
        "每个兑换码仅可使用一次": "Each code can be used once",
        "每轮最多附加 20 份研究材料。": "You can attach up to 20 research materials per turn.",
        "比较可选方案": "Compare options",
        "永久删除账户": "Permanently delete account",
        "永久删除账户、研究任务与个人模型交互记录。此操作无法恢复。": "Permanently delete your account, research tasks, and personal model interactions. This cannot be undone.",
        "永久删除账户？": "Permanently delete account?",
        "永久删除这项研究？": "Permanently delete this research?",
        "没有其他活跃会话": "No other active sessions",
        "没有匹配的项目": "No matching projects",
        "没有找到匹配的记录。": "No matching history found.",
        "注销": "Delete",
        "活跃会话": "Active sessions",
        "浅色": "Light",
        "消息": "Messages",
        "深入研究": "Deep research",
        "深入研究介绍": "Deep research introduction",
        "深度研究现已上线": "Deep Research is now available",
        "深色": "Dark",
        "添加内容": "Add content",
        "状态待确认": "Status unconfirmed",
        "独立对话": "Independent conversations",
        "理清下一步": "Clarify next steps",
        "生成一次性绑定码": "Generate one-time code",
        "用户文件": "Your files",
        "用户管理": "Users",
        "用时": "Elapsed",
        "用自己的话写身份、交流方式、偏好与边界。支持 Markdown；上面的风格只是起点。": "Describe identity, communication, preferences and boundaries in your own words. Markdown is supported; styles above are starting points.",
        "用量记录": "Usage history",
        "用量记录分页": "Usage history pages",
        "界面语言": "Interface language",
        "登录": "Sign in",
        "登录密码": "Sign-in password",
        "登录已过期，请重新登录。": "Your session expired. Sign in again.",
        "登录已过期，请重新登录后继续。": "Your session expired. Sign in again to continue.",
        "目前不使用研究数据训练模型。此项仅记录未来可选改进计划的授权，可随时撤回。": "Your data is not currently used for training. This records revocable consent for a future optional program.",
        "目标、范围与3个可验证子问题": "Goal, scope and three testable questions",
        "目标、障碍与3个可执行行动": "Goal, obstacles and three actionable steps",
        "知识与研究": "Knowledge & research",
        "知识库": "Knowledge base",
        "知识库建议": "Knowledge base suggestion",
        "知识库资料": "Library material",
        "知识整理": "Organized knowledge",
        "研究": "Research",
        "研究 Agent": "Research Agent",
        "研究 Agent 对话栏": "Research Agent conversation panel",
        "研究上下文": "Research context",
        "研究上下文栏": "Research context panel",
        "研究任务": "Research tasks",
        "研究内容仍然保留。重新连接后即可继续。": "Your research is safe. Reconnect to continue.",
        "研究工具栏": "Research tools",
        "研究建议": "Research suggestion",
        "研究材料": "Research materials",
        "研究材料上传失败。": "Research material upload failed.",
        "研究材料暂时无法加载。": "Research materials are unavailable.",
        "研究画布": "Research canvas",
        "研究结论": "Research findings",
        "研究者": "Researcher",
        "研究角度": "Research angle",
        "研究计划": "Research plan",
        "研究记录": "Research history",
        "研究进度": "Research progress",
        "研究问题": "Research question",
        "研究阶段": "Research stages",
        "研究面板": "Research panel",
        "确认停止": "Stop allowing",
        "确认停用": "Deactivate",
        "确认允许": "Allow",
        "确认删除对话": "Confirm delete conversation",
        "确认删除项目": "Confirm delete project",
        "确认撤销": "Revoke session",
        "确认永久删除": "Permanently delete",
        "确认研究意图": "Confirm research intent",
        "确认解除": "Confirm unlink",
        "确认解除绑定": "Confirm unlink",
        "确认账户中": "Checking account",
        "移动主导航": "Mobile navigation",
        "稍后再说": "Maybe later",
        "章节与证据对应": "Sections mapped to evidence",
        "等待消息": "Ready",
        "简体中文": "Chinese (Simplified)",
        "管理员": "Administrator",
        "管理员还没有设置机器人入口，请在平台中打开上述机器人；不要把绑定码发到群里。": "An administrator has not set the bot link. Open the bot shown above on the platform; never send the code in a group.",
        "管理导航": "Administration",
        "绑定码已作废。": "The binding code has been cancelled.",
        "绑定码已过期，请重新生成。": "The binding code expired. Generate a new one.",
        "绑定聊天平台": "Connect a chat platform",
        "结论、出处与局限": "Findings, sources and limits",
        "继续": "Continue",
        "继续形成研究": "Continue into research",
        "继续研究": "Continue research",
        "继续编辑": "Keep editing",
        "缩小研究问题": "Focus the question",
        "网页": "Web page",
        "聊天平台尚未启用。管理员配置官方机器人后，入口会显示在这里。": "Chat platforms are not enabled yet. Configured official bots will appear here.",
        "联网已开启": "Web on",
        "联网搜索": "Web search",
        "自然语言是入口。需要证据时，我会把本次会话的检索过程和来源放在这里。": "Natural language is the starting point. When evidence is needed, retrieval activity and sources for this conversation appear here.",
        "补充方向": "Add a direction",
        "角色": "Character",
        "角色形象": "Character",
        "角色预览": "Character preview",
        "角色颜色": "Color",
        "解除后此账号不能继续使用你的 Agent，该平台未使用的绑定码也会作废。已发送的内容不会撤回。": "This account will lose access to your Agent and unused codes for this bot will expire. Already sent messages cannot be recalled.",
        "解除绑定": "Unlink",
        "订阅": "Subscription",
        "设置": "Settings",
        "设置分类": "Settings category",
        "试用中": "Trial",
        "试试看": "Try it",
        "说话方式": "Speaking style",
        "请先结束当前回答或材料上传，再删除项目": "Finish the current answer or upload before deleting this project",
        "请输入兑换码。": "Enter a redemption code.",
        "请选择可用的模型和强度。": "Choose an available model and reasoning effort.",
        "读取对话": "Loading",
        "调用失败": "Failed",
        "账户": "Account",
        "账户、研究任务、派生文档与个人模型交互记录将被永久删除。删除后无法恢复。": "Your account, research tasks, derived documents, and personal model interaction records will be permanently deleted. This cannot be undone.",
        "账户已停用。": "Account deactivated.",
        "账户已永久删除。": "Account permanently deleted.",
        "账户类型": "Account type",
        "账户菜单": "Account menu",
        "账户设置": "Account settings",
        "账户设置分区": "Account settings sections",
        "账户邮箱": "Account email",
        "费用": "Cost",
        "资料已保存。": "Profile saved.",
        "赠送额度": "Welcome allowance",
        "越高想得越久，适合需要推理的问题": "Higher effort takes longer and suits questions that need reasoning.",
        "跟随系统": "System",
        "跳到主要内容": "Skip to main content",
        "跳过": "Skip",
        "输入": "input",
        "输出": "output",
        "运行管理": "Operations",
        "返回修改": "Return to edit",
        "返回研究面板": "Back to research panel",
        "还没有对话": "No conversations yet",
        "还没有活动": "No activity yet",
        "还没有研究任务": "No research tasks yet",
        "还没有研究记录": "No research yet",
        "还没有绑定的聊天账号。": "No chat accounts are linked.",
        "这份研究材料已删除，原文不再可访问。": "This research material was deleted and its source text is no longer available.",
        "这次回答还没有引用你选择的文件。": "This answer has not cited your selected files yet.",
        "这次回答还没有引用知识库资料。": "No library materials cited yet.",
        "这次回答还没有读取网页。": "No web pages read yet.",
        "这段对话暂时无法打开。你可以从一个新问题继续。": "This conversation cannot be opened right now. You can continue with a new question.",
        "这轮回答未完成，可以从保存的位置重试。": "This answer did not finish. Retry from the saved state.",
        "进入工作空间": "Enter a workspace",
        "进行中": "In progress",
        "连接": "Connections",
        "退出所有设备并暂停访问。研究数据保留，管理员可在核验后恢复账户。": "Sign out all devices and pause access. Your data is retained; an administrator can restore access.",
        "退出登录": "Sign out",
        "退款": "Refund",
        "选择一条来源": "Select a source",
        "选择一条来源后，这里会显示它的依据。": "Select a source to inspect its basis here.",
        "选择机器人": "Choose a bot",
        "选择模型与思考强度": "Choose model and reasoning effort",
        "选择深度研究，自动让 Agent 规划任务，检索你的知识库并阅读网页。你可以查看来源，在文稿中继续编辑结果。": "Use Deep Research to plan a task, search your library, and read web sources. Inspect citations and continue editing the result in your document.",
        "选择项目": "Choose project",
        "通用起步建议": "General starting points",
        "通知": "Notifications",
        "通知分类": "Notification categories",
        "通知栏": "Notifications panel",
        "邮箱": "Email",
        "部署管理员保护": "Deployment admin protection",
        "采用最新版本": "Use latest version",
        "重新加载研究": "Reload research",
        "重新生成": "Regenerate",
        "重新设置我的 AI 伙伴": "Set up my AI companion again",
        "重新读取模型": "Reload models",
        "重新走一遍": "Repeat setup",
        "重试": "Try again",
        "重试本轮": "Retry this turn",
        "重试读取对话": "Retry conversations",
        "重试读取研究": "Retry research",
        "问 Everplain": "Ask Everplain",
        "问一个问题": "Ask a question",
        "阶段": "Stage",
        "需要重试": "Needs retry",
        "项目": "Projects",
        "项目列表暂时无法加载": "Projects are unavailable",
        "项目删除失败": "Project could not be deleted",
        "项目名称": "Project name",
        "项目操作": "Project actions",
        "项目暂不可用": "Project unavailable",
        "项目材料": "Materials",
        "项目材料和研究内容将被删除，所属对话会保留为独立对话。": "Project materials and research will be deleted. Conversations will remain as independent conversations.",
        "预留额度已释放": "Reserved allowance released",
        "颜色": "Color",
        "额外购买额度": "Purchased allowance",
        "额度信息暂不可用": "Usage unavailable",
        "首页": "Home",
    ]
    static func text(_ source: String, locale: String) -> String {
        guard locale == "en-US" else { return source }
        if let translated = english[source] { return translated }
        // Dynamic pairs from AccountSettingsPage, ChannelBindingsPanel and RoleIdentityPanel.
        let templates: [(String, String)] = [
            ("^颜色 (#[0-9a-fA-F]{6})$", "Color $1"),
            ("^共 ([0-9]+) 笔$", "$1 total"), ("^第 ([0-9]+) 页$", "Page $1"),
            ("^有效至 (.+)$", "Valid until $1"), ("^最近活动 · (.+)$", "Last active · $1"),
            ("^([0-9]+) 输入 · ([0-9]+) 输出 token$", "$1 input · $2 output token"),
            ("^(.+) 的 AI 伙伴$", "$1’s AI companion"), ("^平台账号：(.+)$", "Platform account: $1"),
            ("^撤销 (.+) 会话$", "Revoke $1 session"),
            ("^(.+) 将立即退出，未保存的操作可能丢失。$", "$1 will be signed out immediately. Unsaved work may be lost."),
            ("^剩余 ([0-9]+) 分 ([0-9]+) 秒，只可使用一次。不要转发给他人。$", "$1m $2s remaining. Single use only. Do not share it.")
        ]
        for (pattern, replacement) in templates {
            if source.range(of: pattern, options: .regularExpression) != nil { return source.replacingOccurrences(of: pattern, with: replacement, options: .regularExpression) }
        }
        return source
    }
}

func epLocalized(_ source: String) -> String { EPInterfaceStrings.text(source, locale: UserDefaults.standard.string(forKey: "qunxue.interface-locale") ?? "zh-CN") }

struct EPText: View {
    let source: String
    @AppStorage("qunxue.interface-locale") private var locale = "zh-CN"
    init(_ source: String) { self.source = source }
    var body: some View { Text(EPInterfaceStrings.text(source, locale: locale)) }
}

struct EPButton: View {
    let title: String
    let role: ButtonRole?
    let action: () -> Void
    init(_ title: String, role: ButtonRole? = nil, action: @escaping () -> Void) { self.title = title; self.role = role; self.action = action }
    var body: some View { Button(role: role, action: action) { EPText(title) } }
}

struct EPLink: View {
    let title: String
    let destination: URL
    init(_ title: String, destination: URL) { self.title = title; self.destination = destination }
    var body: some View { Link(destination: destination) { EPText(title) } }
}

struct EPTextField: View {
    let title: String
    @Binding var text: String
    @AppStorage("qunxue.interface-locale") private var locale = "zh-CN"
    init(_ title: String, text: Binding<String>) { self.title = title; _text = text }
    var body: some View { TextField(EPInterfaceStrings.text(title, locale: locale), text: $text) }
}

struct EPSecureField: View {
    let title: String
    @Binding var text: String
    @AppStorage("qunxue.interface-locale") private var locale = "zh-CN"
    init(_ title: String, text: Binding<String>) { self.title = title; _text = text }
    var body: some View { SecureField(EPInterfaceStrings.text(title, locale: locale), text: $text) }
}
#endif
